config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "recipes#public_recipes"
  get "/public_recipes", to: "recipes#public_recipes"
  get '/shopping_list', to: 'shopping_list#index', as: 'shopping_list'
  post 'toggle_public', to: 'recipes#toggle', as: 'toggle_public'
  resources :users do
  resources :recipes, only: %i[index show new create destroy] do
    resources :recipe_foods, only: %i[create destroy]
  end
end
  resources :foods, only: %i[index show new create destroy] do
  resources :recipe_foods, only: %i[create destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :read, :all

    return unless user.present?

    can :read, :all
    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: { message: "Name can't be null" }
  validates :quantity, numericality: { only_integer: true, greater_than: 0, message: 'Quantity must be greater than 0' }
  validates :measurement_unit, presence: { message: "Measurement unit can't be null" }
  validates :price, presence: { message: "Price can't be null" }
  validates :price, numericality: { only_float: true, greater_than: 0, message: 'Price must be greater than 0' }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods

  validates :name, presence: { message: "Name can't be null" }, length: { maximum: 250 }
  validates :description, presence: { message: "Description can't be null" }
  validates :preparation_time, presence: { message: "Preparation time can't be null" }
  validates :cooking_time, presence: { message: "Cooking time can't be null" }
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  validates :quantity, presence: { message: "Quantity can't be null" }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true, allow_blank: false, length: { maximum: 250 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
  end

  def after_sign_out_path_for(_scope)
    root_path
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
    @foods = current_user.foods.all
  end

  def new
    @food = Food.new
    @current_user = current_user
  end

  def create
    @food = current_user.foods.new(food_params)
    if food_params[:price].to_f.positive?
      if @food.save
        flash[:success] = "#{@food.name} was successfully created"
        redirect_to foods_url
      else
        flash[:alert] = "#{@food.name} was not created"
        redirect_to new_food_url
      end
    else
      flash[:alert] = 'Price must be greater than 0'
      redirect_to new_food_url
    end
  end

  def destroy
    @food = Food.find(params[:id])

    @check_food = RecipeFood.where(food: @food)
    if @check_food.count.positive?
      flash[:alert] = "#{@food.name} belongs to some recipes"
    else
      flash[:alert] = "#{@food.name} was successfully deleted"
      @food.destroy
    end
    redirect_to foods_url
  end

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @users = User.all
    @recipes = Recipe.includes([:user]).where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])

    @recipe_foods = RecipeFood.new(recipe_foods_params)
    @recipe_foods.recipe = @recipe
    # @recipe_foods = @recipe.recipe_foods.build(recipe_foods_params)

    respond_to do |format|
      format.html do
        if @recipe_foods.save
          redirect_to user_recipe_path(current_user, @recipe.id), notice: 'Ingredient saved successfully'
        else
          redirect_to user_recipe_path(current_user, @recipe.id), alert: 'Error, Ingredient not created!'
        end
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.includes(:recipe, :food).find(params[:id])
    @recipe_food.delete

    respond_to do |format|
      format.html do
        redirect_to user_recipe_path(current_user, @recipe.id), notice: 'Ingredient deleted successfully'
      end
    end
  end

  private

  def recipe_foods_params
    params
      .require(:recipe_food)
      .permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.includes(:recipe_foods).find(params[:id])
    @foods = current_user.foods.all
    @recipe_food = RecipeFood.find_by(recipe_id: params[:id])
  end

  def new
    @recipe = Recipe.new
    respond_to do |format|
      format.html { render :new, locals: { recipe: @recipe } }
    end
  end

  def recipe_params
    params
      .require(:recipe)
      .permit(:name, :description, :public, :preparation_time, :cooking_time)
      .merge(user_id: params[:user_id])
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to user_recipe_path(@recipe.user_id, @recipe.id)
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find params[:id]
    @recipe.destroy
    redirect_to user_recipes_path(@recipe.user_id)
  end

  def public_recipes
    @recipes = Recipe.where(public: true)
  end

  def toggle
    recipe = Recipe.find(params[:id])
    puts recipe.public
    recipe.public = !recipe.public
    recipe.save
    recipe.public
    user_recipe_path(current_user, recipe)
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/shopping_list_controller.rb
class ShoppingListController < ApplicationController
  def index
    @total_items = RecipeFood.connection.select_all(
      'SELECT COUNT(DISTINCT "recipe_foods"."food_id") as sum FROM "recipe_foods" '\
      'INNER JOIN recipes ON "recipe_foods"."recipe_id" = recipes.id '\
      "WHERE recipes.user_id = #{current_user.id}"
    )[0]['sum']
    @total_value = RecipeFood.connection.select_all(
      'SELECT  SUM(recipe_foods.quantity * foods.price) '\
      'FROM recipe_foods '\
      'INNER JOIN foods ON recipe_foods.food_id = foods.id '\
      'INNER JOIN recipes ON recipe_foods.recipe_id = recipes.id '\
      "WHERE recipes.user_id = #{current_user.id}"
    )[0]['sum']
    @total_value ||= 0

    @items = RecipeFood.connection.select_all(
      'SELECT name, DT.quantity, "f"."measurement_unit", (DT.quantity * price) as total_price FROM foods AS f '\
      'INNER JOIN(SELECT  food_id, SUM(recipe_foods.quantity) as quantity FROM recipe_foods INNER JOIN foods ON '\
      'recipe_foods.food_id = foods.id group by food_id)as DT ON f.id = DT.food_id '\
      "WHERE f.user_id = #{current_user.id}"
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.erb
<div class="overflow-x-auto">
  <div class="min-w-screen min-h-screen bg-gray-100 flex pt-20 justify-center bg-gray-100 font-sans overflow-hidden">
    <div class="w-full lg:w-5/6">
      <%= link_to 'Add new food', new_food_path,class: "inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
      <div class="bg-white shadow-md rounded my-6">
        <table class="min-w-max w-full table-auto">
          <thead>
            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
              <th class="py-3 px-6 text-left">Food</th>
              <th class="py-3 px-6 text-left">Unit</th>
              <th class="py-3 px-6 text-center">Price</th>
              <th class="py-3 px-6 text-center">Quantity</th>
              <th class="py-3 px-6 text-center">Action</th>
            </tr>
          </thead>
          <tbody class="text-gray-600 text-sm font-light">
            <% @foods.each do |food| %>
              <tr class="border-b border-gray-200 hover:bg-gray-100">
                <td class="py-3 px-6 text-left whitespace-nowrap">
                  <div class="flex items-center">
                    <span class="font-medium"><%= food.name%></span>
                  </div>
                </td>
                <td class="py-3 px-6 text-left">
                  <div class="flex items-center">
                    <span class="bg-green-200 text-green-600 py-1 px-3 rounded-full text-xs"><%= food.measurement_unit%></span>
                  </div>
                </td>
                <td class="py-3 px-6 text-center">
                  <div class="flex items-center justify-center">
                   <%=number_to_currency food.price%>
                  </div>
                </td>
                <td class="py-3 px-6 text-center">
                  <div class="flex items-center justify-center">
                 <%= food.quantity%>
                  </div>
                </td>
                <td class="py-3 px-6 text-center">
                  <div class="flex item-center justify-center">
                    <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                      <%= button_to food, method: :delete do %>
                       <span >
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-5">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                            
                        </svg>
                        </span>
                        <%end%>
                      </div>
                    </div>
                  </td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://unpkg.com/flowbite@latest/dist/flowbite.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/@themesberg/flowbite@1.1.0/dist/flowbite.min.css" />
    <%= javascript_include_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class=" bg-gray-100">
    <% if current_user %>
      <%= render partial: "shared/navbar" %>
    <%end%>
    <main >
      <div class="overflow-x-auto">
        <div class="min-w-screen min-h-screen  flex justify-center font-sans overflow-hidden">
          <div class="w-full ">
            <div class="ml-5 container w-full flex text-right mt-3 absolute z-50 lg:w-1/3">
              <% if notice %>
                <div class="alert bg-yellow-100 rounded-lg py-5 px-6 mb-3 text-base text-yellow-700 inline-flex items-center w-full alert-dismissible fade show" role="alert">
                  <strong class="mr-1">Notice: </strong> <%= notice %>
                  <button type="button" class="btn-close box-content w-4 h-4 p-1 ml-auto text-yellow-900 border-none rounded-none opacity-50 focus:shadow-none focus:outline-none focus:opacity-100 hover:text-yellow-900 hover:opacity-75 hover:no-underline" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              <%end%>
              <% if  alert %>
                <div class="alert bg-yellow-100 rounded-lg py-5 px-6 mb-3 text-base text-yellow-700 inline-flex items-center w-full alert-dismissible fade show" role="alert">
                  <strong class="mr-1">Alert: </strong> <%= alert %>
                  <button type="button" class="btn-close box-content w-4 h-4 p-1 ml-auto text-yellow-900 border-none rounded-none opacity-50 focus:shadow-none focus:outline-none focus:opacity-100 hover:text-yellow-900 hover:opacity-75 hover:no-underline" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
              <%end%>
            </div>
            <%= yield %>
          </div>
        </div>
      </div>
    </main>
    <script src="https://unpkg.com/flowbite@latest/dist/flowbite.js"></script>
    <script src="https://unpkg.com/@themesberg/flowbite@1.1.0/dist/flowbite.bundle.js"></script>
  </body>
</html>

app/views/recipes/public_recipes.html.erb
 <% if !current_user %>
  <%= link_to "Sign In", new_user_session_path %>
  <%= link_to "Sign Up", new_user_registration_path %>
<% end %>
<div class="relative overflow-hidden bg-no-repeat bg-cover" style="background-position: 50%; background-image: url('https://mdbootstrap.com/img/new/textures/full/142.jpg'); height: 300px;"></div>
<div class="mx-auto px-6 md:px-12 xl:px-32">
  <div class="text-center text-gray-800">
    <div class="block rounded-lg shadow-lg px-6 py-12 md:py-16 md:px-12" style="margin-top: -170px; background: hsla(0, 0%, 100%, 0.7); backdrop-filter: blur(30px);">
      <h1 class="text-5xl md:text-6xl xl:text-7xl font-bold tracking-tight mb-12">Easily keep track of  <br />
        <span class="text-blue-600">Foods and Recipes</span></h1>
      <%= link_to 'Add food', new_food_path, class:"inline-block px-7 py-3 mb-2 md:mb-0 mr-0 md:mr-2 bg-blue-600 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"%>
      <%= link_to  "Add Recipe", new_user_recipe_path(current_user), class:"inline-block px-7 py-3 text-white font-medium text-sm leading-snug bg-transparent text-blue-600 font-medium text-xs leading-tight uppercase rounded hover:text-blue-700 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:ring-0 active:bg-gray-200 transition duration-150 ease-in-out" %>
    </div>
  </div>
</div>
<div class="flex flex-wrap mt-10 ">
  <% @recipes.each do |recipe| %>
    <div class="block   w-full  lg:w-1/3">
      <%= link_to user_recipe_path(recipe.user_id, recipe)  do %>
        <div class="m-5 p-6 rounded-lg shadow-lg bg-white">
          <h5 class="text-gray-900 text-xl leading-tight font-medium mb-2">  <%= recipe.name%></h5>
          <p class="text-gray-700 text-base mb-4">
            By: <%= recipe.user.name %>
          </p>
          <% @recipe_foods = RecipeFood.joins(:food, :recipe).where(food: { user: recipe.user_id }, recipe: { user: recipe.user_id }) %>
          <% @total_items = @recipe_foods.where(recipe_id: recipe.id).count %>
          <% @total_cost = @recipe_foods.where(recipe_id: recipe.id).sum('food.quantity * food.price') %>
          <div class="text-gray-900 text-lg leading-tight font-medium mb-2">Total Food Items: <%= @total_items%></div>
          <div class="text-gray-900 text-lg leading-tight font-medium mb-2">Total Price: <%=number_to_currency @total_cost%></div>
        </div>
      <%end%>
    </div>
  <%end%>
</div>

app/views/recipes/show.html.erb
<div class="overflow-x-auto">
  <div class="min-w-screen min-h-screen bg-gray-100 flex pt-20 justify-center bg-gray-100 font-sans overflow-hidden">
    <div class="w-full lg:w-5/6">
      <div class="block rounded-lg shadow-lg bg-white px-6 py-12 md:px-12 ">
        <div class="actions text-center mb-6">
          <strong>Recipe Name: </strong><%= @recipe.name  %>
        </div>
        <div class="text-right">
          <div class="flex justify-end">
            <div class="mr-5">
              <strong>Public:</strong>
            </div>
            <div>
              <% if can? :manage, @recipe %>
                <%= button_to toggle_public_path(id:@recipe.id),:method => :post, data: { turbo: false } do%>
                  <%if @recipe.public %>
                    <label for="toggle-example-checked" class="flex items-center cursor-pointer relative">
                      <input type="checkbox" id="toggle-example-checked" class="sr-only" checked="">
                      <div class="toggle-bg bg-gray-200 border-2 border-gray-200 h-6 w-11 rounded-full"></div>
                    </label>
                  <% else %>
                    <label for="toggle-example" class="flex items-center cursor-pointer relative mb-4">
                      <input type="checkbox" id="toggle-example" class="sr-only">
                      <div class="toggle-bg bg-gray-200 border-2 border-gray-200 h-6 w-11 rounded-full"></div>
                    </label>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="mb-6">Preparation time <%= @recipe.preparation_time  %> hours</div>
        <div class="mb-6">Cooking time <%= @recipe.cooking_time  %> hours</div>
        <div class="mb-6">Steps go here...</div>
        <div class="flex flex-row mb-6">
          <div class="flex gap-6">
            <% if @recipe.user_id == current_user.id %>
              <div class="flex justify-content-center align-items-center gap-6 my-5 pb-4">
                <%=link_to 'Generate shopping list', shopping_list_path, class: " inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
                <%= render 'ingredient' %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="actions  mb-6">
          <div><strong>Description: </strong></div>
          <p><%= @recipe.description %></p>
        </div>
      </div>
      <div class="bg-white shadow-md rounded my-6">
        <table class="min-w-max w-full table-auto">
          <thead>
            <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
              <th class="py-3 px-6 text-left">Food</th>
              <th class="py-3 px-6 text-left">Quantity</th>
              <th class="py-3 px-6 text-left">Value</th>
              <th class="py-3 px-6 text-center">Action</th>
            </tr>
          </thead>
          <tbody class="text-gray-600 text-sm font-light">
            <% @recipe.recipe_foods.each do |recipe| %>
              <tr class="border-b border-gray-200 hover:bg-gray-100">
                <td class="py-3 px-6 text-left whitespace-nowrap">
                  <div class="flex items-center">
                    <%= recipe.food.name %>
                  </div>
                </td>
                <td class="py-3 px-6 text-left">
                  <div class="flex items-center">
                    <%= recipe.quantity %>
                  </div>
                </td>
                <td class="py-3 px-6 text-left">
                  <div class="flex items-center">
                    <%=number_to_currency recipe.quantity * recipe.food.price %>
                  </div>
                </td>
                <td class="py-3 px-6 text-center">
                  <div class="flex item-center justify-center">
                    <div class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110">
                      <% if current_user.id == recipe.recipe.user_id %>
                        <%= button_to user_recipe_recipe_food_path(current_user, @recipe, recipe), method: :delete,data: { confirm: 'Are you sure?' } do %>
                          <span >
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-5">
                              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                            </svg>
                          </span>
                        <%end%>
                      <% end %>
                    </div>
                  </div>
                </td>
              </tr>
            <%end%>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<section>

    <nav class="navbar navbar-expand-lg shadow-md py-2 bg-white relative flex items-center w-full justify-between">
      <div class="px-6 w-full flex flex-wrap items-center justify-between">
        <div class="flex items-center">
  
          <a class="navbar-brand text-blue-600" href="/">
            <svg class="w-5 h-5 ml-2 lg:ml-0 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
              <path fill="currentColor" d="M485.5 0L576 160H474.9L405.7 0h79.8zm-128 0l69.2 160H149.3L218.5 0h139zm-267 0h79.8l-69.2 160H0L90.5 0zM0 192h100.7l123 251.7c1.5 3.1-2.7 5.9-5 3.3L0 192zm148.2 0h279.6l-137 318.2c-1 2.4-4.5 2.4-5.5 0L148.2 192zm204.1 251.7l123-251.7H576L357.3 446.9c-2.3 2.7-6.5-.1-5-3.2z"></path>
            </svg>
          </a>
        </div>
        <div class="navbar-collapse collapse grow items-center" id="navbarSupportedContentY">
          <ul class="navbar-nav mr-auto lg:flex lg:flex-row">
            <li class="nav-item">
              <%= link_to "Foods", foods_path, class: "nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out" %>
            </li>
            <li class="nav-item">
              <%= link_to  "Recipes", user_recipes_path(current_user), class: "nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out"  %>
            </li>
            <li class="nav-item mb-2 lg:mb-0">
             <%= link_to  "Public Recipes", public_recipes_path(), class: "nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out"  %>
            </li>
            <li class="nav-item mb-2 lg:mb-0">
             <%= link_to  "Shopping List", shopping_list_path, class: "nav-link block pr-2 lg:px-2 py-2 text-gray-600 hover:text-gray-700 focus:text-gray-700 transition duration-150 ease-in-out"  %>
            </li>
          </ul>
          
        </div>
        <div class="flex items-center lg:ml-auto">
          
          <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false },class: "inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out" %>
        </div>
      </div>
    </nav>

   
  </section>

app/views/users/index.html.erb
 <% if !current_user %>
  <%= link_to "Sign In", new_user_session_path %>
  <%= link_to "Sign Up", new_user_registration_path %>
<% end %>
<div class="relative overflow-hidden bg-no-repeat bg-cover" style="background-position: 50%; background-image: url('https://mdbootstrap.com/img/new/textures/full/142.jpg'); height: 500px;"></div>
<div class="container mx-auto px-6 md:px-12 xl:px-32">
  <div class="text-center text-gray-800">
    <div class="block rounded-lg shadow-lg px-6 py-12 md:py-16 md:px-12" style="margin-top: -170px; background: hsla(0, 0%, 100%, 0.7); backdrop-filter: blur(30px);">
      <h1 class="text-5xl md:text-6xl xl:text-7xl font-bold tracking-tight mb-12">Easily keep track of  <br />
        <span class="text-blue-600">Foods and Recipes</span></h1>
       <%= link_to 'Add food', new_food_path, class:"inline-block px-7 py-3 mb-2 md:mb-0 mr-0 md:mr-2 bg-blue-600 text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"%>
      <a class="inline-block px-7 py-3 text-white font-medium text-sm leading-snug bg-transparent text-blue-600 font-medium text-xs leading-tight uppercase rounded hover:text-blue-700 hover:bg-gray-100 focus:bg-gray-100 focus:outline-none focus:ring-0 active:bg-gray-200 transition duration-150 ease-in-out" data-mdb-ripple="true" data-mdb-ripple-color="light" href="#!" role="button">Add Recipe</a>
    </div>
  </div>
</div>
<div class="flex flex-wrap mt-10 ">
 <% @users.each do |user| %>
 <div class="block   w-full  lg:w-1/3">
  <div class="m-5 p-6 rounded-lg shadow-lg bg-white">
    <h5 class="text-gray-900 text-xl leading-tight font-medium mb-2"><%= user.name ? user.name : "Unknown"%></h5>
    <p class="text-gray-700 text-base mb-4">
      Some quick example text to build on the card title and make up the bulk of the card's
      content.
    </p>
     <%= link_to  "Show", user_path(user.id), class: " inline-block px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out"  %>
  </div>
  </div>
<%end%>
</div>